pipeline:
    build:
        image: node:16
        commands:
            - npm i pnpm -g
            - pnpm i
    lint:
        image: node:16
        commands:
            - pnpm lint
    test:
        image: node:16
        environment:
            - COVERALLS_SERVICE_NAME="Codeberg CI"
        commands:
            - pnpm test
            - export COVERALLS_SERVICE_NUMBER=$CI_BUILD_NUMBER
            - export COVERALLS_SERVICE_JOB_NUMBER=$CI_JOB_NUMBER
            - export COVERALLS_GIT_BRANCH=$CI_COMMIT_BRANCH
        secrets:
            - COVERALLS_REPO_TOKEN
