pipeline:
    build:
        image: node:18
        commands:
            - npm i pnpm -g
            - pnpm i
            - pnpm build
    lint:
        image: node:18
        commands:
            - npm run lint
    test:
        image: satantime/puppeteer-node:lts
        commands:
            - npm run test
