pipeline:
    deploy:
        image: node:16
        commands:
            - npx vercel --prod --token=$VERCEL_TOKEN
        secrets:
            - VERCEL_PROJECT_ID
            - VERCEL_ORG_ID
            - VERCEL_TOKEN
        when:
            path:
                include: [.woodpecker/*, www/*]
            branch: main
