pipeline:
    deploy:
        image: node:16
        commands:
            - npm run deploy
        secrets:
            - VERCEL_PROJECT_ID
            - VERCEL_ORG_ID
            - VERCEL_TOKEN
        when:
            path:
                include: ['.woodpecker/*', 'apps/docs/*']
            event: push
            branch: main
