pipeline:
    build:
        image: node:16
        commands:
            - npm i pnpm -g
            - cd www
            - pnpm i
            - pnpm build
    deploy:
        image: ubuntu
        commands:
            - apt update && apt install git rsync -y
            - ./scripts/deploy-website.sh
        secrets:
            - CODEBERG_TOKEN
        when:
            path: www/*
            branch: main
