name: Sync Codeberg.org Mirror

on:
    push:
    workflow_dispatch:

jobs:
    sync-mirror:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Mirror
              run: |
                  git clone --mirror https://github.com/retronav/ixora.git /tmp/ixora
                  cd /tmp/ixora
                  git remote add codeberg https://retronav:$CODEBERG_TOKEN@codeberg.org/retronav/ixora.git
                  git remote update
                  # FIXME: Probably shouldn't force push
                  git push --mirror -u codeberg
              env:
                  CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
